baseURL = 'https://techra.probytace.com/'
languageCode = 'en-us'
title = 'Techra'
disqusShortname = 'techra'

summaryLength = 20
googleAnalytics = ''

[pagination]
  pagerSize = 8

[taxonomies]
  tag = 'tags'
  category = 'categories'
  company = 'companies'
  sector = 'sectors'

[params]
  description = 'Techra delivers sharp coverage of technology, startups, innovation, and digital culture.'
  mainSections = ['posts']

  [params.author]
  name = 'neuralshyam'
  bio = 'Independent writer exploring technology, science, and environmental ideas through practical tools, systems thinking, and grounded experimentation.'
  avatar = '/shyam.jpg'

[sitemap]
  changefreq = 'weekly'
  priority = 0.5
  filename = 'sitemap.xml'

[mediaTypes]
  [mediaTypes."application/rss+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "index"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]


[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Startups'
  pageRef = '/companies'
  weight = 40

[[menus.main]]
  name = 'Sectors'
  pageRef = '/sectors'
  weight = 50

[[menus.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 60

[[menus.main]]
  name = 'About'
  pageRef = '/about'
  weight = 80

[module]
  [module.hugoVersion]
    min = '0.116.0'
